# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user_profile_avatars/'),
        ),
    ]
