# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
        ('users', '0004_auto_20170604_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows_users',
            field=models.ManyToManyField(blank=True, through='relationships.UserFollowsUser', to='users.UserProfile'),
        ),
    ]
