# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20170606_1202'),
        ('relationships', '0003_auto_20170607_0722'),
        ('users', '0006_auto_20170606_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows_boards',
            field=models.ManyToManyField(blank=True, through='relationships.UserFollowsBoard', to='boards.Board'),
        ),
    ]
