# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170606_1118'),
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollowsuser',
            unique_together=set([('follower', 'following')]),
        ),
    ]
