# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-28 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0002_auto_20180728_1437'),
        ('relationships', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowsuser',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='userfollowsuser',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='userfollowsboard',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='userfollowsboard',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board'),
        ),
        migrations.AlterUniqueTogether(
            name='userfollowsuser',
            unique_together=set([('follower', 'following')]),
        ),
        migrations.AlterUniqueTogether(
            name='userfollowsboard',
            unique_together=set([('follower', 'following')]),
        ),
    ]
