# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20170606_1202'),
        ('users', '0006_auto_20170606_1118'),
        ('relationships', '0002_auto_20170606_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowsBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userfollowsboard',
            unique_together=set([('follower', 'following')]),
        ),
    ]
