# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-28 19:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pins.helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=2000, validators=[django.core.validators.URLValidator()])),
                ('image_file', models.ImageField(blank=True, upload_to=pins.helpers.update_filename)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='boards.Board')),
            ],
        ),
    ]
