# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20170601_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='image_file',
            field=models.ImageField(default='', upload_to='pin_images/'),
            preserve_default=False,
        ),
    ]
