# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_auto_20170606_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
