# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import pins.models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0006_auto_20170612_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=pins.models.update_filename),
        ),
    ]
