# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='board',
            unique_together=set([('user_profile', 'name')]),
        ),
    ]
