# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('boards', '0002_auto_20170601_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
    ]
